title: Stephen Schmidt's Bio
author: Stephen Schmidt
email: sschmidt6@uiowa.edu
description: > # this means to ignore newlines until "baseurl:"
  My name is Stephen Schmidt. I am a first year student in the Master of Science - Business Analytics program at the 
  University of Iowa Tippie College of Business. I did my u ndergraduate degree in Business Administration at the 
  University of Northern Iowa and I am currently a part-time data analyst in the Office of Statewide Clinical
  Education Programs (OSCEP) at the University of Iowa Roy J. and Lucille A. Carver College of Medicine.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  sschmidt6 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
